### ISSUE TITLE
A mistake on 2.9. HTTP Authentication (book)

### ISSUE THREAD

**Issue by xucxichpopot** [olegkrivtsov/using-zend-framework-3-book#1]
Hello,

I saw that you have a mistake as below:
![image](https://cloud.githubusercontent.com/assets/8206462/18079757/898331ea-6ebc-11e6-9e1f-d405915dd9d4.png)

I think that we need to add that lines to .htaccess file, it should be as below:
![image](https://cloud.githubusercontent.com/assets/8206462/18079849/ed0676aa-6ebc-11e6-8959-880d931f8b07.png)

**Comment by olegkrivtsov** [comment]
You can put that lines in both Apache virtual host file and in `.htaccess`. If you put them in virtual host, it will look like below:

```
<VirtualHost *:80>
    DocumentRoot /path/to/helloworld/public

    <Directory /path/to/helloworld/public/>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        AuthType Basic
        AuthName "Authentication Required"
        AuthUserFile /usr/local/apache/passwd/passwords
        Require valid-user
    </Directory>

</VirtualHost>
```

It is better to put those lines in virtual host, because that way you do not need to modify your own files.

Does this work for you?

**Comment by xucxichpopot** [comment]
Thanks Oleg Krivtsov, Your e-book is very interesting for me.

I'm newbie in PHP. I will try to do the way you guide.

2016-08-30 17:40 GMT+07:00 Oleg Krivtsov notifications@github.com:

**Comment by xucxichpopot** [comment]
It works for me, Olegkrivtsov. Thanks again.

**Comment by olegkrivtsov** [comment]
Glad to hear. OK, I'll close this issue.
