### ISSUE TITLE
ControllerFactory

### ISSUE THREAD

**Issue by naprstek** [olegkrivtsov/using-zend-framework-3-book#10]
I found somewhere abstract controller factory which use reflection to instantiate controllers. It may simplify an application.

use Interop\Container\ContainerInterface;
use ReflectionClass;
use Zend\ServiceManager\Factory\AbstractFactoryInterface;

class AbstractControllerFactory implements AbstractFactoryInterface
{
    public function __invoke(ContainerInterface $container, $requestedName, array $options = null)
    {
        // Construct a new ReflectionClass object for the requested action
        $reflection = new ReflectionClass($requestedName);
        // Get the constructor
        $constructor = $reflection->getConstructor();

        if (is_null($constructor)) {
            // There is no constructor, just return a new class
            return new $requestedName;
        }

        // Get the parameters
        $parameters = $constructor->getParameters();
        $dependencies = [];
        foreach ($parameters as $parameter) {
            // Get the parameter class
            $class = $parameter->getClass();
            // Get the class from the container
            $dependencies[] = $container->get($class->getName());
        }

        // Return the requested class and inject its dependencies
        return $reflection->newInstanceArgs($dependencies);
    }

    public function canCreate(ContainerInterface $container, $requestedName)
    {
        // Only accept Controller classes
        list( $module, ) = explode('\\', __NAMESPACE__, 2);
        return strstr($requestedName, $module . '\Controller') !== false;
    }
}

and then in module.config.php just list abstract factory:

    'controllers' => [
        'abstract_factories' => [
            AbstractControllerFactory::class,
        ]
    ],

**Comment by olegkrivtsov** [comment]
Abstract factory is not very good because of performance reasons. It is better to use `Zend\Mvc\Controller\LazyControllerAbstractFactory` in your case. 

I think that "lazy" factory *may* simplify controller creation sometimes, but not always. Will think of extending the book text anyway. Thanks!

**Comment by olegkrivtsov** [comment]
I've extended the Website Operation and Model-View-Controller chapters to better describe factories (and particularly the `LazyControllerAbstractFactory`.
