### ISSUE TITLE
Advanced controller configuration

### ISSUE THREAD

**Issue by naprstek** [olegkrivtsov/using-zend-framework-3-book#11]
Whatever application uses logging and very often caching or other services (doctrine?). How to pass this services to every controller and not add thousands parameters to the constructors? Similar way like default session manager in chapter 15.3.2.

**Comment by olegkrivtsov** [comment]
Good question. 

> How to pass this services to every controller and not add thousands parameters to the constructors?

In ZF2, there was `ServiceLocator` pattern allowing to get dependencies from service manager in any part of your app (in controllers, services, etc.) In ZF3, you have to pass dependencies explicitly (this means you have to pass every dependency to every controller). It is not too difficult, and it removes "hidden" dependencies and makes your code easier to understand. If you don't want to pass dependencies manually, use `Zend\Mvc\Controller\LazyControllerAbstractFactory` which can save you some efforts.  

> Similar way like default session manager in chapter 15.3.2.

Default session manager is a legacy feature from ZF1. Actually, I created an issue https://github.com/zendframework/zend-session/issues/58 in `Zend\Session` component where I asked them to remove the default "static" session manager at all. Default session manager creates implicit "hidden" dependencies in your code.  Fortunatelly or unfortunatelly, they do not answer to my request.

**Comment by olegkrivtsov** [comment]
I've extended the Website Operation and Model-View-Controller chapters to better describe factories (and particularly the `LazyControllerAbstractFactory`.
