### ISSUE TITLE
[Proposal] Separate chapter about Events

### ISSUE THREAD

**Issue by seyfer** [olegkrivtsov/using-zend-framework-3-book#12]
Information about working with Events (ListenerAggregates and etc) should be separated in different chapter from chapter about Modules. 
I think so because there is a lot more things to describe and explain, not only usage in context of Module.

**Comment by olegkrivtsov** [comment]
Thanks for your proposal. This book is for beginners, this is not a reference manual. If you need advanced information about events, you can refer to ZF3 documentation.
