### ISSUE TITLE
Two excellent resources - Appendix?

### ISSUE THREAD

**Issue by bitwombat** [olegkrivtsov/using-zend-framework-3-book#14]
Hi Oleg,

There are three excellent ZF3 resources - yours and two others.  I thought maybe there'd be a good place to mention them somewhere?

I have no affiliation - just a dev.

They are:

Alexander Romanenko
https://www.youtube.com/user/integral30/playlists

And Matthew Setter
http://www.masterzendframework.com/

**Comment by olegkrivtsov** [comment]
@bitwombat Thanks for those links. I'll check those tutorials and if I like them/find them compatible with the book, I'll mention them.

**Comment by olegkrivtsov** [comment]
Sorry, not sure how to mention those tutorials in the book.
