### ISSUE TITLE
Need to print it as paperback version using printer, but where is PDF?

### ISSUE THREAD

**Issue by shamun** [olegkrivtsov/using-zend-framework-3-book#15]
Need to print it as paperback version using printer, but where is PDF?
I used `http://www.httrack.com/` but i cant make it as a PDF, can you please give some way to have it also as PDF instead of all individual HTml pages?

**Comment by olegkrivtsov** [comment]
PDF is not available. This is an HTML website. I do not plan to produce a PDF.

**Comment by shamun** [comment]
OK - Thank you no problem.
for internet users who land here via google search and failed to get the information. Here is the hack.

1) PhantomJS get it in Linux or OSX or Windows
2) use URL crawl (http://phantomjs.org/screen-capture.html)

`phantomjs rasterize.js 'http://en.wikipedia.org/w/index.php?title=Jakarta&printable=yes' jakarta.pdf
`

or

```
var page = require('webpage').create();
//viewportSize being the actual size of the headless browser
page.viewportSize = { width: 1024, height: 768 };
//the clipRect is the portion of the page you are taking a screenshot of
page.clipRect = { top: 0, left: 0, width: 1024, height: 768 };
//the rest of the code is the same as the previous example
page.open('http://example.com/', function() {
  page.render('github.png');
  phantom.exit();
});
```

if you need more hack, you can contact me on this, cause i have spent lot of time on this and finally cracked it.

**Comment by r-aamir** [comment]
@shamun hey, possible you could share the crawled version?
