### ISSUE TITLE
Admin dashboard implementation

### ISSUE THREAD

**Issue by webdesign7** [olegkrivtsov/using-zend-framework-3-book#24]
Few posts about creating and admin panel ( eg. displaying all users that should be visible just for admins )  +  admin layout implementation would be helpful to have in this brilliant tutorial too. What you think ? 
Thank you

**Comment by olegkrivtsov** [comment]
Not sure what you mean. In which sample should this appear (User Demo, Blog, etc)?

**Comment by olegkrivtsov** [comment]
Closing this, because there is no response from the reporter.
