### ISSUE TITLE
Shared event manager - reason?

### ISSUE THREAD

**Issue by bitwombat** [olegkrivtsov/using-zend-framework-3-book#48]
Hi Oleg,

In `roledemo/module/User/src/Module.php`, you're grabbing the `sharedEventManager`.  Are you sure this is necessary?  Because you're doing `getApplication()->getEventManager()`, I think you'd be getting the Application's own instance of the event manager (not a new one).  Thus, no need to use the shared functionality.

Other auth examples I've seen just attach to the 'usual' Event Manager.

**Comment by olegkrivtsov** [comment]
Hi @bitwombat Good question. I'm always being confused by the event manager and shared event manager. What I can say - it works, and I don't want to fix it. :)
