### ISSUE TITLE
Query 2 tables with join or separate select statement

### ISSUE THREAD

**Issue by hotbiet** [olegkrivtsov/using-zend-framework-3-book#53]
Hello Oleg,
Thanks for the work. I'm new to ZF3. It helped a lot to understand a lot.
Could you please help me how I could insert a join query from a second table?
I tried it in User \ Entity, but unfortunately without success.
Or do I have to create a second entity file with separate DB Table and then the query in get ..... install.

in zend1 i just took select statements.

thanks
best regards from germany

**Comment by olegkrivtsov** [comment]
You probably need to read a documentation for Doctrine. This is not a issue with this book.

**Comment by hotbiet** [comment]
yes thank you .. I am already reading

**Comment by hotbiet** [comment]
yes thank you .. I am already reading

**Comment by MartinMikac** [comment]
Hi, i have this for join 3 tables.

        $queryBuilder->select('a', 'u','s')
                ->from(Alert::class, 'a')
                ->join('a.user', 'u')
                ->join('u.setting', 's')
                ->where('a.isActive = 1');
  
here you can look for entity structure. :

https://github.com/MartinMikac/KKKV_Panika/tree/master/module/Application/src/Entity


Here is structure of tables. :

![image](https://user-images.githubusercontent.com/22166176/35102342-f83a4b66-fc62-11e7-8e2a-30ad27f4437e.png)

**Comment by hotbiet** [comment]
Thanks Martin, I'll try it tonight and let you know if it works.
